import { Course, BlogPost } from './types';

export const COURSES: Course[] = [
  {
    id: '1',
    title: 'Leadership Mastery',
    description: 'Develop the core competencies of effective leadership, from strategic thinking to emotional intelligence.',
    content: 'Our Leadership Mastery program is designed for current and aspiring leaders who want to make a real difference. You will learn how to build high-performing teams, navigate complex organizational challenges, and develop a leadership style that is both authentic and effective. The curriculum covers strategic decision-making, conflict resolution, and the psychology of motivation.',
    duration: '12 Weeks',
    level: 'Advanced',
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '2',
    title: 'Personal Growth & Resilience',
    description: 'A transformative journey to build self-awareness, emotional strength, and a growth mindset.',
    content: 'This course is a deep dive into the self. You will explore the psychological foundations of resilience, learn how to overcome limiting beliefs, and develop a toolkit for managing stress and adversity. Through a series of reflective exercises and practical workshops, you will build a stronger, more resilient version of yourself.',
    duration: '8 Weeks',
    level: 'Beginner',
    image: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '3',
    title: 'Effective Communication',
    description: 'Master the art of clear, persuasive, and empathetic communication in both personal and professional settings.',
    content: 'Communication is the cornerstone of all successful relationships. This program teaches you how to articulate your ideas with clarity, listen with empathy, and influence others with integrity. You will learn the nuances of non-verbal communication, the art of storytelling, and how to handle difficult conversations with grace.',
    duration: '6 Weeks',
    level: 'Intermediate',
    image: 'https://images.unsplash.com/photo-1521791136064-7986c2959213?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '4',
    title: 'Strategic Career Planning',
    description: 'Design your career path with purpose, clarity, and actionable steps for long-term success.',
    content: 'Stop reacting to career opportunities and start creating them. Our Strategic Career Planning course helps you align your professional goals with your personal values. You will conduct a comprehensive skills assessment, map out potential career trajectories, and develop a networking strategy that opens doors to new possibilities.',
    duration: '10 Weeks',
    level: 'Intermediate',
    image: 'https://images.unsplash.com/photo-1454165833767-027ff39c167a?auto=format&fit=crop&q=80&w=800',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'The Power of Vulnerability in Leadership',
    excerpt: 'Why showing your human side is the most courageous thing a leader can do in today\'s workplace.',
    content: 'Vulnerability is often seen as a weakness, but in leadership, it is a profound strength. When leaders are open about their challenges and uncertainties, they create a culture of trust and psychological safety. This article explores how vulnerability fosters innovation, strengthens team bonds, and ultimately leads to more resilient organizations.',
    date: 'March 10, 2026',
    author: 'Dr. Sarah Jenkins',
    category: 'Leadership',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=800',
    metaTitle: 'Vulnerability in Leadership: The New Strength | Zenith Academy',
    metaDescription: 'Discover why vulnerability is a key trait for modern leaders. Learn how being open and authentic can build trust and drive innovation in your team.',
  },
  {
    id: '2',
    title: 'Building Habits That Actually Stick',
    excerpt: 'The science behind habit formation and practical strategies to transform your daily routine.',
    content: 'Most people fail at habit formation because they rely on willpower alone. The secret to lasting change lies in understanding the habit loop: cue, craving, response, and reward. We delve into the latest research on neuroplasticity and provide a step-by-step guide to designing habits that become automatic over time.',
    date: 'March 5, 2026',
    author: 'Marcus Thorne',
    category: 'Personal Development',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&q=80&w=800',
    metaTitle: 'The Science of Habit Formation: Strategies for Lasting Change',
    metaDescription: 'Learn the psychological secrets to building habits that stick. Explore the habit loop and neuroplasticity to transform your daily routine effectively.',
  },
  {
    id: '3',
    title: 'Navigating Career Transitions with Grace',
    excerpt: 'How to pivot your career path without losing your sense of identity or professional momentum.',
    content: 'Career transitions can be daunting, but they are also opportunities for immense growth. Whether you are changing industries or moving into a new role, the key is to leverage your transferable skills and maintain a clear sense of purpose. This post offers practical advice on networking, rebranding yourself, and managing the emotional aspects of change.',
    date: 'February 28, 2026',
    author: 'Elena Rodriguez',
    category: 'Career',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=800',
    metaTitle: 'Career Transitions: A Guide to Pivoting with Purpose',
    metaDescription: 'Thinking of a career change? Discover how to navigate transitions with grace, leverage your skills, and maintain momentum in your professional journey.',
  },
];
